version: "3.9"
services:
  elastic-mq:
    container_name: elastic-mq
    image: softwaremill/elasticmq:latest
    ports:
      - "9324:9324"
      - "9325:9325"
  elastic-init:
    image: amazon/aws-cli:latest
    depends_on:
      - elastic-mq
    restart: "no"
    environment:
      AWS_ACCESS_KEY_ID: "FAKEKEYID"
      AWS_SECRET_ACCESS_KEY: "FAKEACCESSKEY"
    entrypoint: [
      "aws",
      "sqs",
      "create-queue",
      "--queue-name",
      "image-gallery-queue-dev",
      "--endpoint-url",
      "http://elastic-mq:9324",
      "--region",
      "us-east-1"
    ]
